### PR TITLE
chore(master): add .desktop file for use with Flatpak

### PR DESCRIPTION
**Pull request by poperigby**
I'm working on a Flatpak for Lampray at https://github.com/poperigby/io.github.chollingworth.Lampray, and it would be nice to have a `.desktop` file for better system integration.

### CODE REVIEW

**Comment by airtonix** [comment]
wouldn't it just be better to add the flatpak manifest here and update the release pipeline so this repo creates and publishes it?

**Comment by poperigby** [comment]
Yeah, that would work fine I think.

**Comment by airtonix** [comment]
> Yeah, that would work fine I think. Would you like me to make a PR with manifest, or add it to this one?

👍🏻 

on it.

i think this pr can stay in flight

**Comment by CHollingworth** [comment]
any of the logo variants would work nicely https://github.com/CHollingworth/Lampray/tree/master/logo

**Comment by poperigby** [comment]
> any of the logo variants would work nicely https://github.com/CHollingworth/Lampray/tree/master/logo

Yeah. I was just going to copy those to /app/share/icons when building.

**Comment by poperigby** [comment]
> on it

@airtonix To clarify, would you like me to submit a PR with the manifest?

**Comment by airtonix** [comment]
@poperigby Feel free to contribute to https://github.com/CHollingworth/Lampray/pull/123 if you can otherwise use the `suggestion` feature.


question about the pr title here (since it has impact on the generated changelog and resulting release version:

`<TYPE>(<SCOPE>)` , yours: `chore(master)`.

I think `chore` is right, but since i've not used conventional commits with scopes much before, was there some reason why you chose `master` for the scope? (just trying to see if i missed something). 

My understanding of the scope part, that it should help describe what part of the project (the component) this change affects.

is that right?

**Comment by poperigby** [comment]
> Feel free to contribute to https://github.com/CHollingworth/Lampray/pull/123. if you can, otherwise use the suggestion feature.

Sure!

> question about the pr title here (since it has impact on the generated changelog and resulting release version:

Oops, sorry. I was just following what the other PRs were named like for the scope. I'm not super familiar with how conventional commits work either.

**Comment by airtonix** [comment]
> Oops, sorry. I was just following what the other PRs were named like for the scope. I'm not super familiar with how conventional commits work either.

Don't apologise. I thought there was something you knew that I didn't.

**Comment by airtonix** [comment]
@poperigby but in terms of next steps, i think update the desktop file to accurately point at the logo.

for now it might be safe to assume that this one singular desktop file is only used for the flatpak distro. In future i can imagine that there might be other forms of packaging.

**Comment by poperigby** [comment]
> @poperigby but in terms of next steps, i think update the desktop file to accurately point at the logo.
> 
> for now it might be safe to assume that this one singular desktop file is only used for the flatpak distro. In future i can imagine that there might be other forms of packaging.

Do you mean just putting `lampray` instead of the reverse DNS named icon?

**Pull request closed without merging**
